module.exports = {
  tutorialSidebar: [
        'intro',
        'App',
    {
      type: 'category',
      label: 'Views',
      collapsible: true,
      collapsed: true,
      items: [
        'views/StartView',
        'views/HomeView',
        'views/AboutView',
        'views/ResetPassword'
      ],
    },
    {
      type: 'category',
      label: 'Start',
      collapsible: true,
      collapsed: true,
      items: [
        'start/Login',
        'start/SignUp',
        'start/ForgotPassword'
      ],
    },
    {
      type: 'category',
      label: 'Home',
      collapsible: true,
      collapsed: true,
      items: [
        'home/Summary',
        'home/Board',
        'home/AddTask',
        'home/Contacts',
        'home/Help',
      ],
    },
    {
      type: 'category',
      label: 'Board Components',
      collapsible: true,
      collapsed: true,
      items: [
        'home/BoardComponents/BoardCard',
        'home/BoardComponents/BoardTaskDetail',
        
      ],
    },
    {
      type: 'category',
      label: 'Add Task Components',
      collapsible: true,
      collapsed: true,
      items: [
        'home/AddTaskComponents/AddTaskMain',
        'home/AddTaskComponents/Title',
        'home/AddTaskComponents/Description',
        'home/AddTaskComponents/Category',
        'home/AddTaskComponents/CategoryNew',
        'home/AddTaskComponents/AssignContacts',
        'home/AddTaskComponents/DueDate',
        'home/AddTaskComponents/PrioButtons',
        'home/AddTaskComponents/Subtasks',
      ],
    },
    {
      type: 'category',
      label: 'Contacts Components',
      collapsible: true,
      collapsed: true,
      items: [
        'home/ContactsComponents/Contactslist',
        'home/ContactsComponents/ContactslistCard',
        'home/ContactsComponents/ContactMainContent',
        'home/ContactsComponents/ContactOverlay',
      ],
    },
    {
      type: 'category',
      label: 'Shared Components',
      collapsible: true,
      collapsed: true,
      items: [
        'shared/Header',
        'shared/MenuContainer',
        'shared/Profil',
        'shared/EditProfil',
        'shared/ChangePassword',
        'shared/WorkspaceInfo',
        'shared/CreateNewWorkspace',
        'shared/JoinWorkspace',
        'shared/InviteToWorkspace',
        'shared/SwitchWorkspace',
        'shared/LeaveWorkspaceConfirmation',
        'shared/LegalNotice',
        'shared/PrivacyPolicy',
        'shared/GlobalConfirmationOverlay',
        'shared/GlobalLoadingOverlay',
        'shared/DarkBackground',
        'shared/FormLayout',
        'shared/InputField',
        'shared/AssignedToAvatars',
      ],
    },
    {
      type: 'category',
      label: 'Composables',
      collapsible: true,
      collapsed: true,
      items: [
        'composables/useWorkspaces',
        'composables/useWorkspaceData',
        'composables/useContacts',
        'composables/useConfirmationOverlay',
        'composables/useLoadingOverlay',
        'composables/useTextColor',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      collapsible: true,
      collapsed: true,
      items: [
       'services/workspaceService',
       'services/workspaceDataService',
       'services/contactsService',
      ],
    },
  ]
}
